/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokergame;
import java.util.ArrayList;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author zhang
 */
public class PlayGUI extends javax.swing.JFrame {

static int game_start=1;
private String u_name;
private int u_id;
private int num_bot=0;
private int draw_count=1;
private int house_draw_count=1;
Deck d1= new Deck();
private Player p1 = new Player(null,null,null, new Hand());
private Player bot = new Player(null,null,null, new Hand());
    /**
     * Creates new form PlayGUI
     */
    public PlayGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bottom_panel = new javax.swing.JPanel();
        status = new javax.swing.JTextField();
        game_play = new javax.swing.JPanel();
        ai_rank_1 = new javax.swing.JLabel();
        ai_rank_2 = new javax.swing.JLabel();
        ai_rank_3 = new javax.swing.JLabel();
        ai_rank_4 = new javax.swing.JLabel();
        ai_rank_5 = new javax.swing.JLabel();
        ai_rank_6 = new javax.swing.JLabel();
        rank_1 = new javax.swing.JLabel();
        rank_2 = new javax.swing.JLabel();
        rank_3 = new javax.swing.JLabel();
        rank_4 = new javax.swing.JLabel();
        rank_5 = new javax.swing.JLabel();
        rank_6 = new javax.swing.JLabel();
        action_draw = new javax.swing.JButton();
        action_stand = new javax.swing.JButton();
        hand_pic = new javax.swing.JLayeredPane();
        hand_1 = new javax.swing.JLabel();
        hand_2 = new javax.swing.JLabel();
        hand_3 = new javax.swing.JLabel();
        hand_4 = new javax.swing.JLabel();
        hand_5 = new javax.swing.JLabel();
        hand_6 = new javax.swing.JLabel();
        ai_hand_1 = new javax.swing.JLabel();
        ai_hand_2 = new javax.swing.JLabel();
        ai_hand_3 = new javax.swing.JLabel();
        ai_hand_4 = new javax.swing.JLabel();
        ai_hand_5 = new javax.swing.JLabel();
        ai_hand_6 = new javax.swing.JLabel();
        menu_frame = new javax.swing.JInternalFrame();
        name_input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        start_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        bottom_panel.setPreferredSize(new java.awt.Dimension(800, 600));

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        game_play.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        game_play.setEnabled(false);
        game_play.setInheritsPopupMenu(true);
        game_play.setPreferredSize(new java.awt.Dimension(800, 600));

        ai_rank_1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        ai_rank_1.setForeground(new java.awt.Color(255, 0, 51));
        ai_rank_1.setLabelFor(hand_1);
        ai_rank_1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        ai_rank_2.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        ai_rank_2.setForeground(new java.awt.Color(255, 0, 51));
        ai_rank_2.setLabelFor(ai_hand_2);
        ai_rank_2.setToolTipText("");

        ai_rank_3.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        ai_rank_3.setForeground(new java.awt.Color(255, 0, 51));
        ai_rank_3.setLabelFor(ai_hand_3);
        ai_rank_3.setToolTipText("");

        ai_rank_4.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        ai_rank_4.setForeground(new java.awt.Color(255, 0, 51));
        ai_rank_4.setLabelFor(hand_4);
        ai_rank_4.setToolTipText("");

        ai_rank_5.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        ai_rank_5.setForeground(new java.awt.Color(255, 0, 51));
        ai_rank_5.setLabelFor(hand_5);
        ai_rank_5.setToolTipText("");

        ai_rank_6.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        ai_rank_6.setForeground(new java.awt.Color(255, 0, 51));
        ai_rank_6.setLabelFor(rank_6);
        ai_rank_6.setToolTipText("");

        rank_1.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        rank_1.setForeground(new java.awt.Color(255, 0, 51));
        rank_1.setLabelFor(hand_1);
        rank_1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        rank_2.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        rank_2.setForeground(new java.awt.Color(255, 0, 51));
        rank_2.setLabelFor(hand_2);
        rank_2.setToolTipText("");

        rank_3.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        rank_3.setForeground(new java.awt.Color(255, 0, 51));
        rank_3.setLabelFor(hand_2);
        rank_3.setToolTipText("");

        rank_4.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        rank_4.setForeground(new java.awt.Color(255, 0, 51));
        rank_4.setLabelFor(hand_2);
        rank_4.setToolTipText("");

        rank_5.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        rank_5.setForeground(new java.awt.Color(255, 0, 51));
        rank_5.setLabelFor(hand_2);
        rank_5.setToolTipText("");

        rank_6.setFont(new java.awt.Font("Dialog", 3, 36)); // NOI18N
        rank_6.setForeground(new java.awt.Color(255, 0, 51));
        rank_6.setLabelFor(hand_2);
        rank_6.setToolTipText("");

        action_draw.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        action_draw.setText("Hit");
        action_draw.setEnabled(false);
        action_draw.setVisible(false);
        action_draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_drawActionPerformed(evt);
            }
        });

        action_stand.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        action_stand.setText("Stand");
        action_stand.setEnabled(false);
        action_stand.setVisible(false);
        action_stand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                action_standActionPerformed(evt);
            }
        });

        hand_pic.setPreferredSize(new java.awt.Dimension(800, 600));

        hand_1.setToolTipText("");

        ai_hand_1.setToolTipText("");

        javax.swing.GroupLayout hand_picLayout = new javax.swing.GroupLayout(hand_pic);
        hand_pic.setLayout(hand_picLayout);
        hand_picLayout.setHorizontalGroup(
            hand_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hand_picLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(hand_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ai_hand_1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hand_1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hand_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hand_picLayout.createSequentialGroup()
                        .addComponent(hand_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hand_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hand_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hand_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hand_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(hand_picLayout.createSequentialGroup()
                        .addComponent(ai_hand_2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ai_hand_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ai_hand_4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ai_hand_5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ai_hand_6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        hand_picLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hand_1, hand_2, hand_3, hand_4, hand_5, hand_6});

        hand_picLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ai_hand_1, ai_hand_2, ai_hand_3, ai_hand_4, ai_hand_5, ai_hand_6});

        hand_picLayout.setVerticalGroup(
            hand_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hand_picLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hand_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hand_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ai_hand_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ai_hand_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ai_hand_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ai_hand_3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ai_hand_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ai_hand_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(118, 118, 118)
                .addGroup(hand_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hand_picLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(hand_1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(hand_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hand_4, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(hand_3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(hand_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hand_6, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        hand_picLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hand_1, hand_2});

        hand_picLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hand_4, hand_5, hand_6});

        hand_pic.setLayer(hand_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(hand_2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(hand_3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(hand_4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(hand_5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(hand_6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(ai_hand_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(ai_hand_2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(ai_hand_3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(ai_hand_4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(ai_hand_5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        hand_pic.setLayer(ai_hand_6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout game_playLayout = new javax.swing.GroupLayout(game_play);
        game_play.setLayout(game_playLayout);
        game_playLayout.setHorizontalGroup(
            game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(game_playLayout.createSequentialGroup()
                .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(game_playLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(game_playLayout.createSequentialGroup()
                                .addComponent(action_draw, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(game_playLayout.createSequentialGroup()
                                .addComponent(rank_1)
                                .addGap(103, 103, 103)
                                .addComponent(rank_2)
                                .addGap(110, 110, 110)
                                .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ai_rank_3)
                                    .addGroup(game_playLayout.createSequentialGroup()
                                        .addComponent(rank_3)
                                        .addGap(109, 109, 109)
                                        .addComponent(rank_4)))
                                .addGap(23, 23, 23)))
                        .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(game_playLayout.createSequentialGroup()
                                .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(game_playLayout.createSequentialGroup()
                                        .addGap(86, 86, 86)
                                        .addComponent(rank_5))
                                    .addComponent(action_stand))
                                .addGap(98, 98, 98)
                                .addComponent(rank_6))
                            .addGroup(game_playLayout.createSequentialGroup()
                                .addComponent(ai_rank_4)
                                .addGap(100, 100, 100)
                                .addComponent(ai_rank_5))))
                    .addGroup(game_playLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ai_rank_1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(ai_rank_6)
                .addGap(128, 128, 128))
            .addGroup(game_playLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(ai_rank_2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(game_playLayout.createSequentialGroup()
                    .addComponent(hand_pic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 150, Short.MAX_VALUE)))
        );

        game_playLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {action_draw, action_stand});

        game_playLayout.setVerticalGroup(
            game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(game_playLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ai_rank_1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ai_rank_2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ai_rank_3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ai_rank_4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ai_rank_6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ai_rank_5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(action_draw, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(action_stand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rank_1)
                    .addComponent(rank_2)
                    .addComponent(rank_3)
                    .addComponent(rank_4)
                    .addComponent(rank_5)
                    .addComponent(rank_6))
                .addGap(170, 170, 170))
            .addGroup(game_playLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(game_playLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(hand_pic, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        menu_frame.setVisible(true);

        name_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_inputActionPerformed(evt);
            }
        });

        jLabel1.setText("Player Name:");

        start_btn.setText("Start");
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });

        jLabel2.setText("Player");

        jLabel3.setText("Score");

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel4.setText("Player");

        jLabel5.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel5.setText("Player");

        jLabel6.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel6.setText("Player");

        jLabel9.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel9.setText("Score");

        jLabel10.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel10.setText("Score");

        jLabel11.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel11.setText("Score");

        jLabel14.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel14.setText("Player");

        jLabel15.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel15.setText("Player");

        jLabel16.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel16.setText("Score");

        jLabel17.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel17.setText("Score");

        javax.swing.GroupLayout menu_frameLayout = new javax.swing.GroupLayout(menu_frame.getContentPane());
        menu_frame.getContentPane().setLayout(menu_frameLayout);
        menu_frameLayout.setHorizontalGroup(
            menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_frameLayout.createSequentialGroup()
                .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menu_frameLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                        .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(menu_frameLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(menu_frameLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(menu_frameLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addGap(75, 75, 75)
                .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(114, 114, 114))
        );
        menu_frameLayout.setVerticalGroup(
            menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_frameLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11))
                .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menu_frameLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(menu_frameLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menu_frameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))))
                .addContainerGap(160, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bottom_panelLayout = new javax.swing.GroupLayout(bottom_panel);
        bottom_panel.setLayout(bottom_panelLayout);
        bottom_panelLayout.setHorizontalGroup(
            bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(status)
            .addGroup(bottom_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottom_panelLayout.createSequentialGroup()
                    .addComponent(game_play, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );
        bottom_panelLayout.setVerticalGroup(
            bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottom_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottom_panelLayout.createSequentialGroup()
                    .addComponent(game_play, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 53, Short.MAX_VALUE)))
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Rules");
        contentsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentsMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottom_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bottom_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void endGameDisable()
    {
        action_draw.setEnabled(false);
        action_stand.setEnabled(false);
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogresult = JOptionPane.showConfirmDialog (null, "Would you like to restart another round of the game?","Restart?",dialogButton);
    if (dialogButton == 0) 
    {
        game_start=0;
    }
    else 
    {
        System.exit(0);
    }
    }
    
    private Icon picMatcher(Card cd)
    {
        if(cd instanceof Club)
        {
            Icon type = new ImageIcon(getClass().getResource("/image/club.png"));
            System.out.println("A card in your hand said \"I'm a Club\"");
            return type;
        }        
        else if(cd instanceof Heart)
        {
            Icon type = new ImageIcon(getClass().getResource("/image/heart.png"));
            System.out.println("A card in your hand said \"I'm a Heart\"");
            return type;
        }
        else if(cd instanceof Spade)
        {
            Icon type = new ImageIcon(getClass().getResource("/image/spade.png"));
            System.out.println("A card in your hand said \"I'm a Spade\"");
            return type;
        }
        else if(cd instanceof Diamond)
        {
            Icon type = new ImageIcon(getClass().getResource("/image/diamond.png"));
            System.out.println("A card in your hand said \"I'm a Diamond\"");
            return type;
        }
        else
        {
            System.out.println("I'm nothing");
            return null;
        }
    }
    
    private String rankMatcher(Card cd)
    {
        String result=null;
        switch(cd.toString())
        {
            case "1":
                result="A";
                return result;
            case "2":
                result="2";
                return result;
            case "3":
                result="3";
                return result;
            case "4":
                result="4";
                return result;
            case "5":
                result="5";
                return result;
            case "6":
                result="6";
                return result;
            case "7":
                result="7";
                return result;
            case "8":
                result="8";
                return result;
            case "9":
                result="9";
                return result;
            case "10":
                result="10";
                return result;
            case "11":
                result="J";
                return result;
            case "12":
                result="Q";
                return result;
            case "13":
                result="K";
                return result;
            default:
                return null;
        }

    }
    
    private void houseDealer(Player us)
    {
                switch(draw_count){
            case 1:
                draw_count=draw_count+1;
                us.draw(d1);
                rank_3.setText(rankMatcher(us.seeHand(2)));   
                hand_3.setIcon(picMatcher(us.seeHand(2)));
                break;
                
            case 2:
                draw_count=draw_count+1;
                us.draw(d1);
                rank_4.setText(rankMatcher(us.seeHand(3)));   
                hand_4.setIcon(picMatcher(us.seeHand(3)));
                break;
                
            case 3:
                draw_count=draw_count+1;
                us.draw(d1);
                rank_5.setText(rankMatcher(us.seeHand(4)));   
                hand_5.setIcon(picMatcher(us.seeHand(4)));
                break;
                
            case 4:
                draw_count=draw_count+1;
                us.draw(d1);
                rank_6.setText(rankMatcher(us.seeHand(5)));   
                hand_6.setIcon(picMatcher(us.seeHand(5)));
                break;
                
            default:
                break;
        }  
    }
    private void defaultDealer(Player us)
    {
                switch(house_draw_count){
            case 1:
                house_draw_count+=1;
                us.draw(d1);
                ai_rank_3.setText(rankMatcher(us.seeHand(2)));   
                ai_hand_3.setIcon(picMatcher(us.seeHand(2)));
                break;
                
            case 2:
                house_draw_count+=1;
                us.draw(d1);
                ai_rank_4.setText(rankMatcher(us.seeHand(3)));   
                ai_hand_4.setIcon(picMatcher(us.seeHand(3)));
                break;
                
            case 3:
                house_draw_count+=1;
                us.draw(d1);
                ai_rank_5.setText(rankMatcher(us.seeHand(4)));   
                ai_hand_5.setIcon(picMatcher(us.seeHand(4)));
                break;
                
            case 4:
                house_draw_count+=1;
                us.draw(d1);
                ai_rank_6.setText(rankMatcher(us.seeHand(5)));   
                ai_hand_6.setIcon(picMatcher(us.seeHand(5)));
                break;
                
            default:
                break;
                }
    }
    private void gameInitializer()
    {               
        
        d1.fillDeck();
        d1.deckShuffle();
        p1.draw(d1);
        p1.draw(d1);
        bot.draw(d1);
        bot.draw(d1);
        
        System.out.println(p1.HandRankSum());
        //Player hand initial start
        rank_1.setText(rankMatcher(p1.seeHand(0)));
        rank_2.setText(rankMatcher(p1.seeHand(1)));
        hand_1.setIcon(picMatcher(p1.seeHand(0)));
        hand_2.setIcon(picMatcher(p1.seeHand(1)));
        //Player hand inital ends
        
        //Bot hand initial start    
        ai_hand_1.setIcon(new ImageIcon(getClass().getResource("/image/backside.png")));
        ai_rank_1.setText(rankMatcher(bot.seeHand(0)));
        
        ai_rank_2.setText(rankMatcher(bot.seeHand(1)));
        ai_hand_2.setIcon(picMatcher(bot.seeHand(1)));
        //Bot hand inital end
        ai_rank_1.setVisible(false);
        action_draw.setEnabled(true);
        action_draw.setVisible(true);
        action_stand.setVisible(true);
        action_stand.setEnabled(true);
    }
    
    
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        // TODO add your handling code here:
        
        u_name=name_input.getText();
        menu_frame.dispose();      
        gameInitializer();
        status.setText("Player name is "+u_name+" Player hand sum is: "+p1.HandRankSum()+". ");   
        
    }//GEN-LAST:event_start_btnActionPerformed

    private void name_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_inputActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void action_drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_drawActionPerformed
        // TODO add your handling code here:       
        houseDealer(p1);
        System.out.println("Current player sum is "+p1.HandRankSum());
        if (p1.HandRankSum()==21)
        {
            status.setText("Player hand sum is: "+p1.HandRankSum()+".");
            System.out.println(p1.HandRankSum());
            JOptionPane.showMessageDialog(null, "Player Won", "Result", JOptionPane.PLAIN_MESSAGE);
            endGameDisable();
        }
        else if(p1.HandRankSum()>21)
        {
            status.setText("Player hand sum is: "+p1.HandRankSum()+".");
            System.out.println(p1.HandRankSum());
            JOptionPane.showMessageDialog(null, "Player Bust, House win", "Result", JOptionPane.PLAIN_MESSAGE);
           
            endGameDisable();
        }
        else
        {
            status.setText("Player hand sum is: "+p1.HandRankSum()+".");
        }
    }//GEN-LAST:event_action_drawActionPerformed

    private void action_standActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_action_standActionPerformed
        // TODO add your handling code here:
        System.out.println("Current bot sum is: "+bot.HandRankSum());
        status.setText("Player hand sum is: "+p1.HandRankSum()+". House hand sum is: "+bot.HandRankSum()+".");
        ai_rank_1.setVisible(true);
        ai_hand_1.setIcon(picMatcher(bot.seeHand(0)));
        
        do{
            defaultDealer(bot);            
        }while(bot.HandRankSum()<17);
        
        System.out.println("Bot sum after greater than 17 is"+bot.HandRankSum());
        if(bot.HandRankSum()<21 || bot.HandRankSum()==21)
        {
            if(p1.HandRankSum()>bot.HandRankSum())
            {
                System.out.println("Current bot sum is: "+bot.HandRankSum());
                status.setText("Player hand sum is: "+p1.HandRankSum()+". House hand sum is: "+bot.HandRankSum()+".");
                JOptionPane.showMessageDialog(null, "Player Win", "Result", JOptionPane.PLAIN_MESSAGE);
                endGameDisable();
            }
            else if(p1.HandRankSum()<bot.HandRankSum())
            {
                System.out.println("Current bot sum is: "+bot.HandRankSum());
                status.setText("Player hand sum is: "+p1.HandRankSum()+". House hand sum is: "+bot.HandRankSum()+".");
                JOptionPane.showMessageDialog(null, "House Win", "Result", JOptionPane.PLAIN_MESSAGE);
                endGameDisable();
            }
            else
            {
                System.out.println("Current bot sum is: "+bot.HandRankSum());
                status.setText("Player hand sum is: "+p1.HandRankSum()+". House hand sum is: "+bot.HandRankSum()+".");
                JOptionPane.showMessageDialog(null, "Push", "Result", JOptionPane.PLAIN_MESSAGE);
                endGameDisable();
            }
        }            
        else
        {
            System.out.println("Current bot sum is: "+bot.HandRankSum());
            status.setText("Player hand sum is: "+p1.HandRankSum()+". House hand sum is: "+bot.HandRankSum()+".");
            JOptionPane.showMessageDialog(null, "House Bust, Player Win", "Result", JOptionPane.PLAIN_MESSAGE);
            endGameDisable();
        }
    }//GEN-LAST:event_action_standActionPerformed

    private void contentsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentsMenuItemActionPerformed
        // TODO add your handling code here:
        JDialog rule = new JDialog();
  
    }//GEN-LAST:event_contentsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PlayGUI().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton action_draw;
    private javax.swing.JButton action_stand;
    private javax.swing.JLabel ai_hand_1;
    private javax.swing.JLabel ai_hand_2;
    private javax.swing.JLabel ai_hand_3;
    private javax.swing.JLabel ai_hand_4;
    private javax.swing.JLabel ai_hand_5;
    private javax.swing.JLabel ai_hand_6;
    private javax.swing.JLabel ai_rank_1;
    private javax.swing.JLabel ai_rank_2;
    private javax.swing.JLabel ai_rank_3;
    private javax.swing.JLabel ai_rank_4;
    private javax.swing.JLabel ai_rank_5;
    private javax.swing.JLabel ai_rank_6;
    private javax.swing.JPanel bottom_panel;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel game_play;
    private javax.swing.JLabel hand_1;
    private javax.swing.JLabel hand_2;
    private javax.swing.JLabel hand_3;
    private javax.swing.JLabel hand_4;
    private javax.swing.JLabel hand_5;
    private javax.swing.JLabel hand_6;
    private javax.swing.JLayeredPane hand_pic;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JInternalFrame menu_frame;
    private javax.swing.JTextField name_input;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JLabel rank_1;
    private javax.swing.JLabel rank_2;
    private javax.swing.JLabel rank_3;
    private javax.swing.JLabel rank_4;
    private javax.swing.JLabel rank_5;
    private javax.swing.JLabel rank_6;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton start_btn;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
    
}

